name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions Dependencies
        run: |
          if [ -d "functions" ]; then
            cd functions
            npm install
            cd ..
          fi

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/firebase-key.json"
          firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive.
